# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-601-auto_scaling_group_statically_configured
    comment: '010005032000'
    description: |
      Auto Scaling groups statically configured
    resource: aws.asg
    filters:
      - type: value
        key: MinSize == MaxSize && DesiredCapacity == MinSize && DesiredCapacity == MaxSize
        value: true
